# docker-compose のバージョン
version: '3'

# 各コンテナの情報
services:

  # postgres サービス
  combo-planner_postgres:
    # コンテナの名前
    container_name: combo-planner_postgres
    # Dockerfile のディレクトリパス
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "6432:5432"
    # postgres 設定
    env_file: .env
    volumes:
      - dbdata_sf6-x-media-planner:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # golang アプリケーション
  combo-planner_api:
    container_name: combo-planner_api
    ports:
      - "8080:8080"
    depends_on:
      #CHANGE 2: it prevents issuing a request while the server is starting to depend on the healthy status of postgres-db
      combo-planner_postgres:
        condition: service_healthy
      combo-planner_session:
        condition: service_started
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    env_file: .env
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./:/go/src/github.com/kenkonno/sf6-x-media-planner/backend/
    # docker-compose run 実行時に実行されるコマンド
    tty:
      true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  combo-planner_migration:
    container_name: combo-planner_migration
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
    env_file: .env
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./:/go/src/github.com/kenkonno/sf6-x-media-planner/backend/
    # docker-compose run 実行時に実行されるコマンド
    tty:
      true
    #    command: go run ./main.go
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # postgres サービス
  combo-planner_session:
    # コンテナの名前
    container_name: combo-planner_session
    # Dockerfile のディレクトリパス
    build:
      context: .
      dockerfile: ./docker/session/Dockerfile
    ports:
      - "6379:6379"
    # postgres 設定
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # postgres サービス
  combo-planner_web:
    # コンテナの名前
    container_name: combo-planner_web
    # Dockerfile のディレクトリパス
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    # postgres 設定
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  dbdata_sf6-x-media-planner:
    external: true
