/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

// User - 
type User struct {
	Id *int32 `json:"id,omitempty" form:"id,omitempty"`

	Nickname string `json:"nickname" form:"nickname" binding:"min=1"`

	Email string `json:"email" form:"email" binding:"min=1"`

	Password string `json:"password" form:"password" binding:"min=1"`

	Status string `json:"status" form:"status" binding:"min=1"`

	CreatedAt time.Time `json:"created_at,omitempty" form:"created_at,omitempty"`

	UpdatedAt int64 `json:"updated_at,omitempty" form:"updated_at,omitempty"`
}
