/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/kenkonno/sf6-x-media-planner/backend/api/interactor/users"
	"github.com/kenkonno/sf6-x-media-planner/backend/api/interactor/login"
	"github.com/kenkonno/sf6-x-media-planner/backend/api/interactor/logout"

	"github.com/kenkonno/sf6-x-media-planner/backend/api/openapi_models"
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteUsersId - DeleteUsersId
func DeleteUsersId(c *gin.Context) {
	var r openapi_models.DeleteUsersIdResponse
	r, err := users.DeleteUsersIdInvoke(c)
	if err != nil {
	} else {
		c.JSON(http.StatusOK, r)
	}
}

// GetUsers - GetUsers
func GetUsers(c *gin.Context) {
	var r openapi_models.GetUsersResponse
	r, err := users.GetUsersInvoke(c)
	if err != nil {
	} else {
		c.JSON(http.StatusOK, r)
	}
}

// GetUsersId - GetUsersId
func GetUsersId(c *gin.Context) {
	var r openapi_models.GetUsersIdResponse
	r, err := users.GetUsersIdInvoke(c)
	if err != nil {
	} else {
		c.JSON(http.StatusOK, r)
	}
}

// PostLogin - PostLogin
func PostLogin(c *gin.Context) {
	var r openapi_models.PostLoginResponse
	r, err := login.PostLoginInvoke(c)
	if err != nil {
	} else {
		c.JSON(http.StatusOK, r)
	}
}

// PostLogout - PostLogout
func PostLogout(c *gin.Context) {
	var r openapi_models.PostLogoutResponse
	r, err := logout.PostLogoutInvoke(c)
	if err != nil {
	} else {
		c.JSON(http.StatusOK, r)
	}
}

// PostUsers - PostUsers
func PostUsers(c *gin.Context) {
	var r openapi_models.PostUsersResponse
	r, err := users.PostUsersInvoke(c)
	if err != nil {
	} else {
		c.JSON(http.StatusOK, r)
	}
}

// PostUsersId - PostUsersId
func PostUsersId(c *gin.Context) {
	var r openapi_models.PostUsersIdResponse
	r, err := users.PostUsersIdInvoke(c)
	if err != nil {
	} else {
		c.JSON(http.StatusOK, r)
	}
}
